language: python
python:
  - "3.5"  # Python 3.5 still needs to be installed on Travis-CI

env:
  - TOX_ENV=py27
  - TOX_ENV=py34
  - TOX_ENV=py35
  - TOX_ENV=pypy26
  - TOX_ENV=pep8

install:
  - pip install tox coveralls

script:
  - NOSE_VERBOSE=0 tox -e $TOX_ENV

after_success:
  - coveralls

sudo: false
